Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Documentation:
  Exclude:
    - 'db/**/*'
